### ISSUE TITLE
Installation process broken

### ISSUE THREAD

**Issue by baddiedev** [Atheos/Atheos#163]
**Describe the bug**
I git cloned Atheos to a new website tonight and the installation process seems to be broken. When I navigate to where Atheos is, I get the Initial Setup screen, however when I click the Install button the overlay happens, but the "root path, are you sure" dialog doesn't display so I can't get any further.

Using Dev-Tools in Chrome, after hitting the install button I see a type error saying `self.create is not a function`. I've included a screenshot of the console below.

**To Reproduce**
Steps to reproduce the behaviour:
1. Clone Atheos from Github to public_html/atheos
2. Navigate to example.com/atheos
3. Complete initial setup fields
4. See broken installation

**Expected behaviour**
Log in to Atheos for the first time

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Laptop - ChromeOS / Webhost - Linux
 - Browser: Chrome
 - Version: 89 (stable channel)

**Additional context**
![image](https://user-images.githubusercontent.com/38323743/113081078-e7507680-91cf-11eb-8a17-0d6a76d2cbfa.png)

`

**Comment by HLSiira** [comment]
Thank you for letting me know. I just pushed a fix to the dev branch of Atheos and will merge into master here in a second. I hadn't initialized the new alert module and therefore it wouldn't work correctly.

**Comment by baddiedev** [comment]
Thank you!  I cloned the new master. It seemed to work and the alert came up fine. I'm now presented with further issues which mean I still can't log in for the first time. Should I start a new issue or continue in this one?

**Comment by HLSiira** [comment]
We can use this one if you want

**Comment by baddiedev** [comment]
OK. After completing the Initial Setup with these details...

![image](https://user-images.githubusercontent.com/38323743/113132103-ecd0af80-9215-11eb-8dba-e65a8b075723.png)

all was good and the login page loaded, which I completed with the same details...

![image](https://user-images.githubusercontent.com/38323743/113130525-14267d00-9214-11eb-8d66-54893ffd54e0.png)

But I got a toast that says `Username not found`.

`config.php` looks to have generated correctly. The file structure of `/data` and the contents of `users.json` and `projects.db.json` looks like this...

![image](https://user-images.githubusercontent.com/38323743/113132615-9ca61d00-9216-11eb-9946-78bd16bd6610.png)

So I changed `users.json` and `projects.db.json` to look like this...

![image](https://user-images.githubusercontent.com/38323743/113133219-4edde480-9217-11eb-96cb-c9402cc27a09.png)

But I get the same toast saying `Username not found`.

So I changed the username in `users.json` to be all lowercase and this time when I try login I get a toast saying `Invalid password` instead.

Now I'm out of ideas.

**Comment by HLSiira** [comment]
Try typing in your password in lowercase, just out of curiosity

-------- Original Message --------

**Comment by HLSiira** [comment]
Actually I think they installation process broke completely silently. On [Line 56](https://github.com/Atheos/Atheos/blob/cee195735659ed2741b22aeba02bb64e8f14f535/components/install/init.js#L56) of `components/install/init.js`, the install data isn't being passed to the server. If you add `data` as an arg to `self.install()` and reinstall, the data should be pushed correctly. When I was testing, I must not have tested the absolute pathing statements.

`self.install();` changed to `self.install(data);`

I'll fix it on my end and push to master but I'm not able to test it right now due to other obligations. Later today, I'll spend a bit double checking the installation process.

**Comment by baddiedev** [comment]
Success! Everything went smoothly this time. Thanks so much!

**Comment by HLSiira** [comment]
Sweet, let me know if you run into any problems!
