### ISSUE TITLE
Terminal Plug in Not working

### ISSUE THREAD

**Issue by Shahi-Paneer** [Atheos/Atheos#210]
I manually installed the terminal plug in and it shows up on the right side bar. When I click on it nothing happens...

I've reinstalled it same issue perssist.

Im new to this so if you need any config files to look through let me know and ill supply them.

THe plan is to use codiad for students to be able to write/compile code onto our website we use for comp sci courses.

Thanks

**Comment by HLSiira** [comment]
Can you add more details on your browser / PHP version and web server? Thank you.

**Comment by Shahi-Paneer** [comment]
> Can you add more details on your browser / PHP version and web server? Thank you.

Using Chrome Version 95.0.4638.69 (Official Build) (64-bit).

PHP Version 7.2.34 running on 


NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

Linux version 3.10.0-1160.21.1.vz7.174.13


More details on the issue:

I have gotten the terminal tab to now open in atheos but whenever you enter a command in just says processing and does not do anything. Atheos is functionally perfectly other than the terminal plug in not working.

**Comment by HLSiira** [comment]
Thank you. I'll try to look into it this week, I haven't used the terminal in a while so it's possible it broke over the last few updates. If you don't mind, do you have any errors in the web server logs?

**Comment by Shahi-Paneer** [comment]
> Thank you. I'll try to look into it this week, I haven't used the terminal in a while so it's possible it broke over the last few updates. If you don't mind, do you have any errors in the web server logs?

`[03-Nov-2021 14:20:18 America/Los_Angeles] PHP Fatal error:  Uncaught ErrorException: Non-static method Common::execute() should not be called statically in /home/liemcomputing/public_html/Aethos1/Atheos-5.0.0/components/codegit/traits/execute.php:13
Stack trace:
#0 /home/liemcomputing/public_html/Aethos1/Atheos-5.0.0/components/codegit/traits/execute.php(13): {closure}(8192, 'Non-static meth...', '/home/liemcompu...', 13, Array)
#1 /home/liemcomputing/public_html/Aethos1/Atheos-5.0.0/components/codegit/traits/status.php(7): CodeGit->execute('git status --br...')
#2 /home/liemcomputing/public_html/Aethos1/Atheos-5.0.0/components/codegit/controller.php(27): CodeGit->repoStatus()
#3 /home/liemcomputing/public_html/Aethos1/Atheos-5.0.0/controller.php(41): require('/home/liemcompu...')
#4 {main}
  thrown in /home/liemcomputing/public_html/Aethos1/Atheos-5.0.0/components/codegit/traits/execute.php on line 13`

This seems to keep repeating itself in the logs. Please let me know if you need any more information from my side. 

Also the terminal plug in does not ask for the password as well it seems to go straight into the screenshot I provided before. No authentication required when there is the default password set. 

Not sure if this any use to you but, my use case for the terminal plug-in is so that students can their compile C++, Python, and Java code.

Thanks.

**Comment by Shahi-Paneer** [comment]
> Thank you. I'll try to look into it this week, I haven't used the terminal in a while so it's possible it broke over the last few updates. If you don't mind, do you have any errors in the web server logs?

Hi, sorry to bother , but was wondering if you had any updates on if you were able to get the terminal plug in working yourself?

Question: Does your Atheos account also need to have user (with the exact same creditionals) on the server to access your terminal? because I'm wondering if that is the issue

**Comment by HLSiira** [comment]
Nope because I'm the worst and forgot to look into it.

It runs the commands as the web user so www-data for apache but that's not what it sounds like.

**Comment by Shahi-Paneer** [comment]
> Nope because I'm the worst and forgot to look into it.
> 
> It runs the commands as the web user so www-data for apache but that's not what it sounds like.

haha np. To be honest, I don't really need full terminal functionality. I just need a way for students to be able to compile python, java, and c++ on Atheos if you have any other solutions.  (Final goal is to have 100+ students to be able to work on there coding projects anywhere via browser for our comp sciences courses versus only be limited to school)

My current plan is to give everybody terminal access and allow them to compile through there but I would somehow need to figure out a way for them to only be limited to compile commands and nothing else. So no students break the server hosting the website.

**Comment by HLSiira** [comment]
Hey, I updated the plugin and have it working on my install. The main thing is any compiling commands will need to be able to be run by the web-user, no idea what form that will look like. I'll leave this open as I'm sure there will still be issues lol

**Comment by Shahi-Paneer** [comment]
> Hey, I updated the plugin and have it working on my install. The main thing is any compiling commands will need to be able to be run by the web-user, no idea what form that will look like. I'll leave this open as I'm sure there will still be issues lol


Hi, unfortunately, problem still persists. I reinstalled Terminal by deleting it from the plug-ins folder then installed it through marketplace no luck. I also tried manually reinstalling no luck as well.  When entering in a command and hitting enter it still gets stuck at Processing... It also doesn't ask for any type of authentication  (Not sure if it's supposed to but, I saw something mentioned about a default password).

> I'm really interested to see how they like it and if it works well, I've never had junior users running Atheos, let me know if you run into any hang ups.

Oh yeah definitely, once we can figure out how to compile it we will slowly start moving students over. Atheos is one of the only IDES I could find that is easily self-hosted as well as adds induvial user support. Allowing me to create a project for each user only allowing them access to there user directory.  Also another great thing about Atheos is how it is has very simple ui. It's going to hopefully make our grade 9 - 12 comp science courses a bit smoother.

**Comment by HLSiira** [comment]
Are you still getting the same errors in the apache logs?

**Comment by Shahi-Paneer** [comment]
Yes

**Comment by HLSiira** [comment]
Are you pulling from the master branch to install Atheos or are you using the 5.0 release?

**Comment by Shahi-Paneer** [comment]
> Are you pulling from the master branch to install Atheos or are you using the 5.0 release?

I used this version... ![image](https://user-images.githubusercontent.com/81540701/142557502-c5c9ef3f-9cc3-4595-893d-d73f259221eb.jpeg)

Should I try the master branch instead?

**Comment by HLSiira** [comment]
Yeah if you don't mind. Sorry that you're dealing with this.

**Comment by Shahi-Paneer** [comment]
Ok no problem.

**Comment by Shahi-Paneer** [comment]
> Yeah if you don't mind. Sorry that you're dealing with this.

Fresh install from master branch... no luck. Same issue unfortunately, stuck at processing screen.

**Comment by HLSiira** [comment]
Would you be willing to email me login credentials with dev mode enabled? I understand that is a big ask but it would enable me to see what's going on directly.

**Comment by Shahi-Paneer** [comment]
I will email you login details to liam@siira.io.

**Comment by Shahi-Paneer** [comment]
Ok I sent you all the details. Please let me know if you have received it via email or here.

Thank you.

**Comment by HLSiira** [comment]
I think I fixed it, you might need to reset your browser cache in order for it to update but not sure what happened. I have been able to get a lot of basic commands to run but it's been a long long time since I messed with Java but I managed to get the little test java file you created to compile and run in the terminal. 

Honestly not sure what caused the bug, I think the updating and migrating from version to version caused some cache to get stuck, hopefully I was able to shake it loose.

**Comment by Shahi-Paneer** [comment]
Hi,

Unfortunately it is still not working on my end. I have cleared my browser cache as well as try a different device no luck :(. Same issue occurs, stuck at processing screen. Maybe something is wrong on my end? 

![Capture](https://user-images.githubusercontent.com/81540701/142715455-48272839-ac06-4c16-aaa4-897972f112dc.PNG)

File path seems to wrong unless that is just a visual glitch. It should be Aethos1.

Using Browser version: Chrome Version 96.0.4664.45 (Official Build) (64-bit)

**Comment by HLSiira** [comment]
Refresh your browser and try again real quick

I actually just set you up with everything. If you go into `/home/liemcomputing/Aethos1/Atheos-master/plugins/Terminal/terminal.php`, there is a allowed list on line 27.
`define("ENABLED", "java,ls,cd,echo,javac");`

I also set up the marco component to work a little better, though the output leaves a lot to be desired, it does work with the test java files

**Comment by Shahi-Paneer** [comment]
> Refresh your browser and try again real quick

Sucsess! It works! 

> I actually just set you up with everything. If you go into /home/liemcomputing/Aethos1/Atheos-master/plugins/Terminal/terminal.php, there is a allowed list on line 27.
define("ENABLED", "java,ls,cd,echo,javac");

Sounds good, thank you for setting that up.

> I also set up the marco component to work a little better, though the output leaves a lot to be desired, it does work with the test java files

Sounds good. How does the component work exactly... how do you activate them? Sorry if that is bit of a dumb question.

Also, Thank you so much for getting this working. I really appreciate it :)

**Comment by HLSiira** [comment]
Yay!!! Thank you for your patience, I'm really excited to see if Atheos meets your needs or what issues you run into. You have my email and github so if you ever need support or anything, let me know. 

No stupid questions lol

If you right click on a file with a Java extension, it'll compile it. If you right click on a file with a class extension, it'll try to run it.

On the right sidebar is a menu for macro editing, make sure you click the save icon if you edit one.

**Comment by Shahi-Paneer** [comment]
> Yay!!! Thank you for your patience, I'm really excited to see if Atheos meets your needs or what issues you run into. You have my email and github so if you ever need support or anything, let me know.

Ok sounds good! Yeah on Monday we will start with 1 or 2 students, test it out completely and if all goes well it'll be everyone's main IDE. 
 
> No stupid questions lol
> 
> If you right click on a file with a Java extension, it'll compile it. If you right click on a file with a class extension, it'll try to run it.
> 

OK yeah just tested it out and works. Is there any way to see the output or it basically just checks if the program can compile.

> On the right sidebar is a menu for macro editing, make sure you click the save icon if you edit one.

Yup, saw that. I'll try playing around with it over the weekend.

Sorta unrelated but, 

Do you think I can create a script that auto creates users for Atheos if I give it a class list for example in a particular format. ( it would also have to auto create a project for each user)


Username PW /home/liemcomputing/users/(Insert username here)

Or better yet somehow get it to interact with Joomla which is used to manage all the content on the main site to auto create the account when a Joomla account is created. Currently how it works is when an account is created for the website an directory is auto created for the account in /users/ . 
 
None of this stuff is really import to me currently me but, I would like to figure this out down the line as manually creating over 100 accounts will be annoying lol.

**Comment by HLSiira** [comment]
I opened/commented reminders for those requests on some other issues, and I'm going to close this one if you don't mind. I'll see what I can do about adding bulk account creation, but Joomla auth is going to take a while.

**Comment by Shahi-Paneer** [comment]
> I opened/commented reminders for those requests on some other issues, and I'm going to close this one if you don't mind. I'll see what I can do about adding bulk account creation, but Joomla auth is going to take a while.

Hi, 

Been playing around with the plugin terminal and has it was been working great but I've ran into an issue. When trying to compile python scripts that require user input I am met with this error:

`liemcomputing:/home/liemcomputing/public_html/Aethos$ python3.6 python.py
Select operation.
1.Add
2.Subtract
3.Multiply
4.Divide
Enter choice(1/2/3/4): Traceback (most recent call last):
  File "python.py", line 28, in <module>
    choice = input("Enter choice(1/2/3/4): ")
EOFError: EOF when reading a line`

When running straight from the terminal outside of Atheos the script functions correctly.

Here is the script:

`# Program make a simple calculator

# This function adds two numbers
def add(x, y):
    return x + y

# This function subtracts two numbers
def subtract(x, y):
    return x - y

# This function multiplies two numbers
def multiply(x, y):
    return x * y

# This function divides two numbers
def divide(x, y):
    return x / y


print("Select operation.")
print("1.Add")
print("2.Subtract")
print("3.Multiply")
print("4.Divide")

while True:
    # take input from the user
    choice = input("Enter choice(1/2/3/4): ")

    # check if choice is one of the four options
    if choice in ('1', '2', '3', '4'):
        num1 = float(input("Enter first number: "))
        num2 = float(input("Enter second number: "))

        if choice == '1':
            print(num1, "+", num2, "=", add(num1, num2))

        elif choice == '2':
            print(num1, "-", num2, "=", subtract(num1, num2))

        elif choice == '3':
            print(num1, "*", num2, "=", multiply(num1, num2))

        elif choice == '4':
            print(num1, "/", num2, "=", divide(num1, num2))
        
        # check if user wants another calculation
        # break the while loop if answer is no
        next_calculation = input("Let's do next calculation? (yes/no): ")
        if next_calculation == "no":
          break
    
    else:
        print("Invalid Input")`

Thanks

**Comment by HLSiira** [comment]
Unfortunately I think an interactive command like that is beyond the scope of what I can do with PHP execution like that. I'll think about it and see if I come up with a solution but it's unlikely.

**Comment by Shahi-Paneer** [comment]
> Unfortunately I think an interactive command like that is beyond the scope of what I can do with PHP execution like that. I'll think about it and see if I come up with a solution but it's unlikely.

What do you think about implementing something like this into Atheos for terminal use:

https://github.com/xtermjs/xterm.js

https://xtermjs.org/

I know this maybe a long shot but thought I would ask about it

**Comment by HLSiira** [comment]
So XTerm.js is mainly the front end terminal. A really nice interactive terminal for your browser, if I understand the sites correctly. The difficulty stems from the backend. When PHP executes a command, it sends back the reply and the transaction is over. Interactive commands require a back and forth connection, something PHP doesn't really provide in a way I've figured out how to utilize.

WebSockets could facilitate something like that, but they require an active daemon, service, or application running on the actual server, meaning a manual button push on the server somewhere. I don't know much about websockets and have tried to get them working before but never found them really applicable to how Atheos is designed: Drag and Drop installation within the browser. 

I'll keep playing with it, but my only thought would be to package up an entire SSH-browser app in, and then ask you're students to SSH in, but at that point, why not utilize the regular windows terminal? I also don't know the reliability / security of those apps. I'll look into them though, I've always wanted to be able to use more fluid terminal experience within Atheos.

**Comment by Shahi-Paneer** [comment]
> So XTerm.js is mainly the front end terminal. A really nice interactive terminal for your browser, if I understand the sites correctly. The difficulty stems from the backend. When PHP executes a command, it sends back the reply and the transaction is over. Interactive commands require a back and forth connection, something PHP doesn't really provide in a way I've figured out how to utilize.
> 
> 
> 
> WebSockets could facilitate something like that, but they require an active daemon, service, or application running on the actual server, meaning a manual button push on the server somewhere. I don't know much about websockets and have tried to get them working before but never found them really applicable to how Atheos is designed: Drag and Drop installation within the browser. 
> 
> 
> 
> I'll keep playing with it, but my only thought would be to package up an entire SSH-browser app in, and then ask you're students to SSH in, but at that point, why not utilize the regular windows terminal? I also don't know the reliability / security of those apps. I'll look into them though, I've always wanted to be able to use more fluid terminal experience within Atheos.

Hmm I see what you mean. PHP can only send one command then recieve the output where as something with user input you need a more dynamic approach which PHP cannot fully provide.

As for websockets I wouldn't mind using one if it could plugin with Atheos nicley and maintain control of commands. But I understand what you mean with how Atheos is designed it sort of defeats the purpose in a way.

With a built in SSH client that would also work. I don't mind if the students have to go through a couple hoops to log in my main thing is to make everything browser accessible. (some students may not have access to full pcs and only Chromebooks for example. That way keeping everything consistent making it simple to work on the courses)

**Comment by HLSiira** [comment]
So I poked around with this and it might meet your needs: [SSHy](https://github.com/stuicey/SSHy), a "working" fork located here: [Updated SSHy](https://github.com/drgrussell/SSHy)

I couldn't get the websocket to run correctly, but a browser based SSH client has been on my dream sheet for a while, just never found one that really felt right. [webSSH](https://github.com/huashengdun/webssh) seems promising, I might try it later tonight, it also uses xterm and seems REALLY easy to install.

My main concern with something like this is the idea of having public facing free-to-use ssh client, just feels like it's already been hacked by someone and I haven't even installed it yet lol.



I'll check out the terminal opening to other projects thing, it should open up into the project folder that the student is active within, but I'm not sure if there is a prevention measure for keeping them inside their projects or not, it's been a while since I wrote/migrated this plugins.

**Comment by Shahi-Paneer** [comment]
> So I poked around with this and it might meet your needs: [SSHy](https://github.com/stuicey/SSHy), a "working" fork located here: [Updated SSHy](https://github.com/drgrussell/SSHy)
> 
> 
> 
> I couldn't get the websocket to run correctly, but a browser based SSH client has been on my dream sheet for a while, just never found one that really felt right. [webSSH](https://github.com/huashengdun/webssh) seems promising, I might try it later tonight, it also uses xterm and seems REALLY easy to install.
> 
> 
> 
> My main concern with something like this is the idea of having public facing free-to-use ssh client, just feels like it's already been hacked by someone and I haven't even installed it yet lol.
> 
> 
> 
> 
> 
> 
> 
> I'll check out the terminal opening to other projects thing, it should open up into the project folder that the student is active within, but I'm not sure if there is a prevention measure for keeping them inside their projects or not, it's been a while since I wrote/migrated this plugins.

Ok cool, good to hear we might have a solution lol. I see what you mean with that security concern seems a bit risky but doesn't look like we have many other options.

For the terminal folder thingy it was acting a little bit strange. When I moved my folder in the terminal it also moved it for another user when they freshly started there terminal.

**Comment by HLSiira** [comment]
The folders and projects aren't user specific. Atheos is making actual modifications to the folders on the server. Each one of your students will have to have their own project WITHIN the workspace folder if that makes sense. There is only ONE workspace folder.

However, now that you have me thinking about it like that, it seems poor design. It's built around the idea of collaboration, and you can limit users to only certain projects, however there isn't really a method of a private workspace for regular users. I'll have to tinker around with it and see what I come up with.

**Comment by HLSiira** [comment]
The folders and projects aren't user specific. Atheos is making actual modifications to the folders on the server. Each one of your students will have to have their own project WITHIN the workspace folder if that makes sense. There is only ONE workspace folder.

However, now that you have me thinking about it like that, it seems poor design. It's built around the idea of collaboration, and you can limit users to only certain projects, however there isn't really a method of a private workspace for regular users. I'll have to tinker around with it and see what I come up with.

**Comment by Shahi-Paneer** [comment]
> So I poked around with this and it might meet your needs: [SSHy](https://github.com/stuicey/SSHy), a "working" fork located here: [Updated SSHy](https://github.com/drgrussell/SSHy)
> 
> I couldn't get the websocket to run correctly, but a browser based SSH client has been on my dream sheet for a while, just never found one that really felt right. [webSSH](https://github.com/huashengdun/webssh) seems promising, I might try it later tonight, it also uses xterm and seems REALLY easy to install.
> 
> My main concern with something like this is the idea of having public facing free-to-use ssh client, just feels like it's already been hacked by someone and I haven't even installed it yet lol.
> 
> I'll check out the terminal opening to other projects thing, it should open up into the project folder that the student is active within, but I'm not sure if there is a prevention measure for keeping them inside their projects or not, it's been a while since I wrote/migrated this plugins.

Hmm so I tried both [Updated SSHy](https://github.com/drgrussell/SSHy) and [webSSH](https://github.com/huashengdun/webssh) neither of them worked. I am able to ssh in through windows so I do know that the SSH works on the server. I guess its back to the drawing boards for now...

**Comment by HLSiira** [comment]
They both require running some sort of backend process that you have to access and have ports open for I think, took me quite a while to barely get one to work but it was a pretty annoying learning experience
