### ISSUE TITLE
live preview or something... ;)

### ISSUE THREAD

**Issue by N0NameN0** [Atheos/Atheos#281]
is there a "live preview" / "auto refresh" mode or at least a preview shortcut i missed ?

**Comment by N0NameN0** [comment]
i finnaly read the code ;) and discovered a shortcut "CTRL-O" but seems broken.
i fixed it like this in the file modules/keybind.js

`
 // Open in browser [CTRL+O] //////////////////////////////////////80
                        node.bind(79, 'ctrl', function() {
                                let mypath = atheos.active.getPath();
                                atheos.filemanager.openInBrowser({path:mypath});
                        }); 
`

**Comment by HLSiira** [comment]
The problem with the live preview is that there isn't really anyway for the files to work as expected due to the pathing. If you open a file in Atheos from a live preview, you'd have to specify the file paths to utilize whatever directory you're working in relative to whatever directory Atheos is in, and you'd have to setup some sort of constant parsing and adjustment to handle any requests.

**Comment by lucasvieites** [comment]
Hi there, I ended up hee while searching for a preview feature for MarkDown files. I found an old plugin that's still shown as "Coming Soon" in the Atheos Marketplace: [Atheos-MarkdownPreview](https://github.com/HLSiira/Atheos-MarkdownPreview), but it looks abandoned as the last updates were 5 years ago.
I tried it out anyway, but it doesn't seem to do anything. No errors, nothing in the webserver logs...
Am I in the right place to add my "+1" to a preview feature?
