### ISSUE TITLE
CodeGit Non-functional

### ISSUE THREAD

**Issue by HLSiira** [Atheos/Atheos#53]
The Codegit Component has a lot of broken buttons and components. This is due to converting it from a plugin to a component, and trying to do a complete rewrite. It's taking a long time to update all of it's parts and turn it into a manageable component. 

Please leave a comment for things you've noticed are broken and I'll address them as I go.

**Comment by WebCrew** [comment]
For my opinion it would be the best to get rid of the old CodeGit and start a brand new one with the new Git API. Its better to start from scratch as working with a pile of crazy code salat.

In addition, I think that the CodeGit can wait until you have adapted the rest of the base Codiad to your new requirements. I would only do the processing of all plugins at the end when your entire repository has already become more known and more helpers have found it - then it will be easier.

Kind regards, Andy

**Comment by HLSiira** [comment]
Lol I actually am getting really close to being done with most of the rewrites on other components.

CodeGit actually interfaces with the git cli tool pretty cleanly and doesn't appear to be super dated. It's pretty useful as to know the direction to the take the code, but you might be right on starting over.

**Comment by kurim** [comment]
Hey Siira,

do you have any ETA when you will finish GIT Component?

**Comment by HLSiira** [comment]
I'll try to do as much as I can this week. I've been procrastinating on it because it's honestly a really not fun component to work on.

-------- Original Message --------

**Comment by HLSiira** [comment]
Codegit is proving to be the hardest thing I've ever worked on. I think I can get most of the integration working, except for Push/Pull/Fetch where they require authentication. @Andr3as made some really high level complex code in order to make the integration work.

**Comment by ScrumpyJack** [comment]
Would implementing oauth (for git behind githut, gitea or gogs for example) simplify authentication?

**Comment by HLSiira** [comment]
Simplify authentication probably not, but it might be a solution. The way authentication worked currently is that codegit basically stores your github password plain text, and whenever the web server needed it, it would access it and pass it to git. Now I won't touch saving a password plaintext with a 10 foot pole, so one idea I had was just requiring the user to set up SSH keys with their account before git would work, but it seems like saving your password with extra steps almost.

**Comment by ScrumpyJack** [comment]
I would like to use Atheos as a webIDE instead of vim when I am somewhere where I don't have vim, in order to edit files a private git repo that has gitea as a frontend.
Really excited about CodeGit.

**Comment by HLSiira** [comment]
I have two libraries that have been in my queue to start playing around with. Looking through Codegit, it almost is easier to start over as @WebCrew suggested, so since I have next week off, I'm probably going to knock out most of it. I've already tested one library and the other has some good code in it.

I think the goal for next week will be to allow you to basically run all the git commands you can within reason, but the interfaces might be super basic text. One of the hardest parts of working on the git interface is creating an intuitive front end, but if I skip that step and go only for function for now, shouldn't be too hard.

My goals will be to facilitate, in order: Init repos and sub modules, Set and get remotes/branches and Push, Pull, Fetch, and Revert changes. Once I get those done, I'm going to consider the component set and done unless someone wants me to add a feature. Let me know what you think.

Libraries I found: [kbjr's Git.php](https://github.com/kbjr/Git.php) and [czproject's git-php](https://github.com/czproject/git-php)

**Comment by HLSiira** [comment]
In order to facilitate remotes, I've come up with creating ssh keys for your web user. Seems to work pretty well, I haven't had a single issue with the process so far.

Another option I'm trying to get to work is utilizing the personal access token feature of github and gitlab as an alternative to storing your password.

**Comment by kurim** [comment]
Did you test pushing git with atheos?

Since www-data looks like this
![image](https://user-images.githubusercontent.com/1880220/86719097-0a287280-c024-11ea-9be7-a35fc413b2f8.png)

**Comment by HLSiira** [comment]
Oh yeah, Codegit is "working" now, and I've been using it with reckless abandon. I'll need to figure out why it's not using my name though...

**Comment by kurim** [comment]
Btw. does the git settings page still not work?
Also in my posting pull request was a bug...

```php
<?php echo i18n("project_gitnote."); ?>
```
just a "."
```php
<?php echo i18n("project_gitnote"); ?>
```
and in the json file i name it note instead of gitnote

**Comment by HLSiira** [comment]
It's read only if you have it configured, I haven't added the ability to set the details yet, but most of the work is done. I'm still unsure if it's worth my time configuring local vs global settings or not.

The tricky part is the set up; Codegit is going to require you to have SSH keys for your web user and your repos to use SSH unless I can get another component to work but that's later on down the line.

**Comment by kurim** [comment]
> I'm still unsure if it's worth my time configuring local vs global settings or not.

I think config for local should be better, since diffrent projects may have diffrent git hoster.

**Comment by ScrumpyJack** [comment]
![codegit](https://user-images.githubusercontent.com/3187469/87122149-363e3080-c27c-11ea-94fe-50e88bf4806a.png)

This is from a the master branch. I'm on Firefox

**Comment by kurim** [comment]
The text bug is a known "issue",
it solved in current dev. version

**Comment by ScrumpyJack** [comment]
Thanks, yes that work on dev branch. Still can't get anything from codegit though

This is what happens when I click on codegit after a fresh install, and switch to dev branch before creating the user


![cg](https://user-images.githubusercontent.com/3187469/87130121-4f4dde00-c28a-11ea-8595-d01a34869364.png)

**Comment by kurim** [comment]
Can you check the Console Log from your browser while opening the CodeGit?
Also you can check Atheos\data\log\

**Comment by ScrumpyJack** [comment]
Console suggests that pluginsCSS.min.css could not be loaded.
That file seems empty.

{code}
-rw-r--r--  1 nginx www-data      0 Jul 10 08:28 pluginsCSS.min.css
{code}

**Comment by kurim** [comment]
That is not the issue, the file is the same on my side.

`-rw-r--r--  1 www-data www-data      0 Jul  8 09:21 pluginsCSS.min.css`

What did you webserver log show?

**Comment by ScrumpyJack** [comment]
Nothing, only info and warnings, no errors

**Comment by ScrumpyJack** [comment]
Felix, do you want to try it out? Happy to do a fresh install and you can take a look around

**Comment by ScrumpyJack** [comment]
After updating to 4.3 i still see the same problem

**Comment by HLSiira** [comment]
Is the project that you are working in a git repository?

**Comment by ScrumpyJack** [comment]
ah, no, i am just clicking on codegit hoping it will take me to a codegit config where I can edit codegit settings.

I take it that is not the case :) 

Where do I set the path to me ssh key?

**Comment by HLSiira** [comment]
So weird. It should still open up even if its not an active repo.

You'll need to set that up outside of Atheos, I don't want to really enable access to the ssh keys directly via Atheos.
I'm running on Apache on a Linux server, so what I did was copy my `/home/USER/.ssh` folder to `/var/www/.ssh` and then set the permissions of that .ssh folder to be usable by www-data user only.
```
USER@SERVER:/var/www$ ls -la
total 28
drwxr-xr-x  7 root     root     4096 Aug  2 18:20 .
drwxr-xr-x 14 root     root     4096 May 23 12:20 ..
drwxrws--- 11 www-data www-data 4096 Sep  3 15:36 html
drwx------  2 www-data www-data 4096 Jun 27 17:56 .ssh
```


That's keeping in mind that you've already set up your github account to use the ssh keys in your user account.

**Comment by ScrumpyJack** [comment]
I think some other stuff is not quite right, I'll open issues for those before I try getting CodeGit to work
