### ISSUE TITLE
Theme light colors not working

### ISSUE THREAD

**Issue by windows10luke** [Atheos/Atheos#83]
When running version 4.1 of Atheos, any theme that has a white background (e.g. Eclipse, Dreamweaver, Dawn, Clouds) the following characters fail to show up due to the white background: (){}->;[] 
If I highlight a line of code that has any of those characters in it, they show up faintly because of the contrast of the highlight. 
Is there something I am missing to get the light themes to work, or is this a bug that needs to be fixed?

**Comment by HLSiira** [comment]
I think I fixed in the latest push to the development branch; thanks for catching that. I accidentally overwrote the default color for all themes by setting a global color on the editor.

**Comment by windows10luke** [comment]
Thanks for your reply.
I installed the latest from development and the issue still occurs.
Here is what some code looks like with the Eclipse theme:
![Eclipse Theme](https://user-images.githubusercontent.com/40614799/83822923-753afe00-a6a0-11ea-85e7-08bdba911b5f.PNG)

Here is the same code using the default Atheos theme:
![Atheos Theme](https://user-images.githubusercontent.com/40614799/83822984-a4516f80-a6a0-11ea-9397-40a8a2935045.PNG)

I remember installing Atheos back in February of this year and it had this issue then. I am not sure if this is a problem with just my server environment (a default LAMP install), or if this is a bug.

**Comment by HLSiira** [comment]
It should be fixed in the latest push to development, but you need to ensure you refresh your browser cache for it to take effect. If it doesn't take effect after that, let me know. As far as I can tell, I've caught all the things that could be caused by it.

**Comment by windows10luke** [comment]
I completely started over with my installation of Atheos and cleared everything out of my browser cache with no success - the issue still persisted. I looked at some of the CSS code and I think I may have found the issue. The problem lies with the "editor" class in the main.min.css file. The color is set to a white there. When I remove that color element from the class the issue goes away and all the themes work as they should. See below images for reference. 
![Incorrect Atheos Class](https://user-images.githubusercontent.com/40614799/83984354-bc282e00-a902-11ea-94cc-f61ec484838a.PNG)

This is what happens when that class color is ignored:
![Atheos Incorrect Class Corrected](https://user-images.githubusercontent.com/40614799/83984376-e4b02800-a902-11ea-969c-3162e9f58bf1.PNG)

**Comment by HLSiira** [comment]
You nailed it exactly; that's what I came up with as well; however I merged that fix into the master branch. Are you installing from the latest release and not the master/development branches? The Confessor release doesn't have the fix yet but the master branch of Atheos does have it.

https://github.com/Atheos/Atheos/blob/master/themes/atheos/modules/editor/_main.scss#L13

That's the only thing I can think of.

As an aside, would you prefer if Atheos itself had a lighter theme to it overall? I think I might be able to implement a dark/light mode to Atheos pretty easily.

**Comment by windows10luke** [comment]
You are correct. It turns out that for some reason, I was always pulling from the master branch and not the development branch. After getting the development branch version, it works as expected.

I actually prefer coding in a light environment, as I am more used to that. However, having the file manager and settings menus dark is excellent, as I prefer a darker theme for everything else. Having just migrated from Codiad, I find Atheos to be so much more enjoyable to use with its more advanced feature set. I greatly appreciate all the work that has been put into this project, and thank you for all your help with this.

**Comment by HLSiira** [comment]
Thanks, let me know if you have any issues. I think I'll try to add some custom color theme options soon either way.
